### ISSUE TITLE
Custom form only in new record

### ISSUE THREAD

**Issue by enfJoao** [SCullman/DNN.FormAndList#4]
Hey.

Is it possible to apply the custom form template to the edit record also, instead of new record only?

Best regards,
João

**Comment by SCullman** [comment]
No,thats not possible 

Gesendet von meinem Windows 10 Phone

Von: eXistenZe
Gesendet: Donnerstag, 3. August 2017 18:15
An: SCullman/DNN.FormAndList
Cc: Subscribed
Betreff: [SCullman/DNN.FormAndList] Custom form only in new record (#4)

Hey.
Is it possible to apply the custom form template to the edit record also, instead of new record only?
Best regards,
João
